name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vérification structure
        run: echo "Structure OK"

      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1
